remote_theme: jekyll/jemmistakes/minimal-mistakes 
title: Um passo para a criatividade
description: A prática para desenhar projetos, prever custos e avançar sem medo
github:
  is_project_page: false
