remote_theme: pages-themes/Minima
title: Miriam Ferreira | Formação em Gestão de Projetos
description: Formação prática para desenhar projetos, prever orçamentos e avançar sem medo
github:
  is_project_page: false
